### ISSUE TITLE
Improve functionality of close()

### ISSUE THREAD

**Issue by jhkolb** [SoftwareDefinedBuildings/bw2android#1]
Currently, calling `close` on a BosswaveClient instance does not stop the auxiliary thread that invokes callbacks. This is because stopping a thread in Java is non-trivial.

We can resolve this by adding a timeout to the underlying socket read.

**Comment by kaifeichen** [comment]
right on

**Comment by jhkolb** [comment]
This should be fixed as of cc361a6.
